### ISSUE TITLE
Doubts 

### ISSUE THREAD

**Issue by GuilhermeMorais** [xamarin/GooglePlayServicesComponents#17]
Guys, I just found this great initiative and start to ask myself, this project is alive, moreover there is any tutorial/help/link/blog/post/twiit about how to use it?

Thanks a lot in advance.

**Comment by Redth** [comment]
There are many components for Google Play Services on our component store which make it really easy to see Getting Started guides and Sample projects: https://components.xamarin.com/?search=Google+Play+Services

You can also find these samples right in the source code of this repository. Eg: https://github.com/xamarin/GooglePlayServicesComponents/tree/master/maps/samples

Finally, since we bind Google's own API's, they are similar enough that tutorials you find written for Java apps are not too dissimilar to their C# counterparts and are a good place to start if you can't find a Xamarin specific tutorial on the subject you're interested in.

Hope that helps!
