### ISSUE TITLE
PlusClass.PeopleApi.GetCurrentPerson (mGoogleApiClient) predecated!!!

### ISSUE THREAD

**Issue by babman92** [xamarin/GooglePlayServicesComponents#170]
### Describe your Issue:
var people = PlusClass.PeopleApi.GetCurrentPerson (mGoogleApiClient) is deprecated, people returned is null. Talk to me we have an other way to replace this method please. 
Thanks you.

**Comment by Redth** [comment]
Unfortunately, we don't control which API's Google decides to deprecate...

There's some discussion on this particular API here: https://stackoverflow.com/questions/34412157/plus-peopleapi-getcurrentperson-deprecated-in-play-services-8-4-how-to-get-user

Presumably since Google Plus itself is going away, this API will not be replaced.
