### ISSUE TITLE
Nearby: incomplete wrapper

### ISSUE THREAD

**Issue by code-mc** [xamarin/GooglePlayServicesComponents#18]
### Xamarin.Android Version (eg: 6.0):
6.0

### Operating System & Version (eg: Mac OSX 10.11):
Windows 7

### Google Play Services Version (eg: 8.4.0):
N/A

The package version is 29.0.0.2 (= latest stable)

### Describe your Issue:
The Builder class from the MessagesOptions.Builder is missing in the wrapper. This makes it impossible to initiate background scanning for BLE beacons without getting the user's consent. These builder classes are in fact included for all the other APIs that are available in the nearby package. The MessagesOptions.Builder seems to be overlooked when testing the wrapper.

### Steps to Reproduce (with link to sample solution if possible):
The java code for what I'm trying to achieve (from Google Developers here: https://developers.google.com/nearby/messages/android/user-consent)

```java
mGoogleApiClient = new GoogleApiClient.Builder(this)
        .addApi(Nearby.MESSAGES_API, new MessagesOptions.Builder() // <---- this class is not included in the wrapper
            .setPermissions(NearbyPermissions.BLE)
            .build())
        .addConnectionCallbacks(this)
        .enableAutoManage(this, this)
        .build();
```

### Include any relevant Exception Stack traces, build logs, adb logs:
N/A

**Comment by Redth** [comment]
It looks like the `setPermissions` method was not added as of Google Play Services `8.4.0` (our version `29.0.0.2`), which is why you aren't seeing it available.  Though, the `MessageOptions` class itself does exist both in the java lib, and the .NET binding.

I'm not sure exactly which version the `setPermissions` method was added, however if you try our latest -PreRelease version of the nuget package, you will find the binding does contain the `SetPermissions` method you are expecting.  The latest prereleases are based off of Google Play Services `9.4.0`

Hope that helps!
