### ISSUE TITLE
Can't build android project with Xamarin.Firebase.Firestore and modernhttpclient

### ISSUE THREAD

**Issue by TobiasBuchholz** [xamarin/GooglePlayServicesComponents#194]
### Xamarin.Android Version (eg: 6.0):
Minimum: 5.0
Target: 9.0

### Operating System & Version (eg: Mac OSX 10.11):
Mac OSX 10.14.3 

### Describe your Issue:
I'm trying to build an android app which is supposed to use the Xamarin.Firebase.Firestore package and the [modernhttpclient](https://github.com/paulcbetts/ModernHttpClient) package. After adding those two to the project via nuget the build fails with an IllegalArgumentException.

### Steps to Reproduce (with link to sample solution if possible):
- create new android project
- add Xamarin.Firebase.Firestore nuget package
- add modernhttpclient nuget package
- build

or build the [sample project](https://github.com/TobiasBuchholz/ModernFirestore)

### Include any relevant Exception Stack traces, build logs, adb logs:
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error: java.lang.IllegalArgumentException: already added :  Lcom/squareup/okhttp/Address; (ModernFirestore)

**Comment by Redth** [comment]
Looks like ModernHttpClient embeds OkHttp bindings in the nuget package when really it should just be taking a dependency on OkHttp (since Firestore also needs this as a dependency) which is why you're seeing the duplicate class error from java.  You could potentially alternatively manually reference just the ModernHttpClient .dll from the nuget package instead which (might?) work.  Unfortunately ModernHttpClient is not something we own or maintain so there isn't much we can do here.

**Comment by moljac** [comment]
Tried with `modernhttpclient-updated` and sample project was built (BTW thanks for the sample repo that accelerated tests).

I would suggest using `modernhttpclient-updated` because it was updated 9 months ago, so 2018-09, seems to be maintained actively and uses some newer dependencies.

https://www.nuget.org/packages/modernhttpclient-updated/

`modernhttpclient` nuget was not updated since 2015.

https://www.nuget.org/packages/modernhttpclient

It has package dependencies, but the age might cause some problems.

Closing this one.
