### ISSUE TITLE
Error.. Google Play Services - Vision 71.1620.0-preview3 

### ISSUE THREAD

**Issue by pulmuone** [xamarin/GooglePlayServicesComponents#205]
### Xamarin.Android Version (eg: 6.0):
Android 9(Pie)

### Operating System & Version (eg: Mac OSX 10.11):
Win 10

### Google Play Services Version (eg: 8.4.0):
Google Play Services - Vision 71.1620.0-preview3

### Describe your Issue:
Error Source  :
https://github.com/xamarin/GooglePlayServicesComponents/blob/master/samples/com.google.android.gms/play-services-vision/VisionSample/BarcodeScannerActivity.cs

BarcodeScannerActivity.cs

var detector = new BarcodeDetector.Builder (Application.Context)
                        .Build ();

Error Message : 
Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/vision/zzl;

{Java.Lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/vision/zzl; ---> Java.Lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.vision.zzl" on path: DexPathList[[zip file "/data/app/com.xamarin.googleplayservices.visionsample-d8GSZoGJ_737ckX3nrDaag==/base.apk"],nativeLibraryDirectories=[/data/app/com.xamarin.googleplayservices.visionsample-d8GSZoGJ_737ckX3nrDaag==/lib/arm64, /data/app/com.xamarin.googleplayservices.visionsample-d8GSZoGJ_737ckX3nrDaag==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
   --- End of inner exception stack trace ---
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <286213b9e14c442ba8d8d94cc9dbec8e>:0 
  at Android.Gms.Vision.Barcodes.BarcodeDetector+Builder.Build () [0x0000a] in <ae72cb0897a6466d84af956ab0f86db6>:0 
  at VisionSample.BarcodeScannerActivity.OnCreate (Android.OS.Bundle bundle) [0x00038] in E:\Study\Xamarin\play-services-vision\VisionSample\BarcodeScannerActivity.cs:39 
  --- End of managed Java.Lang.NoClassDefFoundError stack trace ---
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/internal/vision/zzl;
	at md5e0309ac3bebcb91dbbfdf45b89258e1e.BarcodeScannerActivity.n_onCreate(Native Method)
	at md5e0309ac3bebcb91dbbfdf45b89258e1e.BarcodeScannerActivity.onCreate(BarcodeScannerActivity.java:32)
	at android.app.Activity.performCreate(Activity.java:7327)
	at android.app.Activity.performCreate(Activity.java:7318)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3251)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7045)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.internal.vision.zzl" on path: DexPathList[[zip file "/data/app/com.xamarin.googleplayservices.visionsample-d8GSZoGJ_737ckX3nrDaag==/base.apk"],nativeLibraryDirectories=[/data/app/com.xamarin.googleplayservices.visionsample-d8GSZoGJ_737ckX3nrDaag==/lib/arm64, /data/app/com.xamarin.googleplayservices.visionsample-d8GSZoGJ_737ckX3nrDaag==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 17 more
}

![Cap 2019-05-02 21-02-03-785](https://user-images.githubusercontent.com/42885949/57074137-fac1e100-6d1d-11e9-9d23-a86945fc1701.png)

**Comment by 61315** [comment]
Try use Google Mobile Vision Barcode detector on Preview2. Some of FirebaseVision related classes are not properly binded and cannot be used currently. Reason I'm mentioning Preview2 is that those working detector classes from Android.Gms.Vision are also not properly binded on Preview3 for some reason.

1. Add nuget package Xamarin.GooglePlayServices.Vision 71.1502.0-preview2
2. Write your script accordingly https://codelabs.developers.google.com/codelabs/bar-codes/#5

It goes like this.

```
using Android.Gms.Vision;
using Android.Gms.Vision.Barcodes;

class YourDetector
{
    BarcodeDetector _detector;

    public YourDetector()
    {
        _detector = new BarcodeDetector.Builder(Application.Context)
            .SetBarcodeFormats(BarcodeFormat.QrCode) //You can change this option.
            .Build();
    }

    public List<Barcode> Detect()
    {
        List<Barcode> barcodes = new List<Barcode>();

        //You have to build a frame from camera capture callback.
        Bitmap image = null; //This bitmap should not be null.
        Frame frame = new Frame.Builder()
            .SetBitmap(image)
            .Build();  

        SparseArray result = _detector.Detect(frame);
        if (result == null || result.Size() == 0)
            return null;
        for (int i = 0; i < result.Size(); ++i)
            barcodes.Add(result.ValueAt(i) as Barcode);

        return barcodes;
    }
}
```

**Comment by moljac** [comment]
Preview3 and Preview2 differ in versions and this is the reason for missing classes. (For those that want to learn something - check the versions of java artifacts in `config.json` in the root of the repo for Preview2 and Preview3).

Google changes their API and we are unfortunately reactive (we have no previews of Google's SDKs in advance).

So, when bindings are done, it is difficult for us to tell that everything is/was surfaced (very few of us know Google APIs by heart and even fewer mapping 1:1 to Xamarin).

**Comment by moljac** [comment]
@pulmuone @61315 
Can you try preview4 please. And provide feedback here

**Comment by pulmuone** [comment]
Xamarin.Android Bindings for Google Play Services - Vision 71.1620.0-preview4

same Error
![Cap 2019-05-09 01-37-16-008](https://user-images.githubusercontent.com/42885949/57392293-5d721b80-71fb-11e9-99a0-430276b02fff.png)

**Comment by pulmuone** [comment]
Same Error
Xamarin.Android Bindings for Google Play Services - Vision 71.1620.0-preview4


![Cap 2019-05-09 01-37-16-008](https://user-images.githubusercontent.com/42885949/57392337-77136300-71fb-11e9-9f8b-7c3e6493d75c.png)

**Comment by pulmuone** [comment]
> @pulmuone @61315
> Can you try preview4 please. And provide feedback here

Same Error
Xamarin.Android Bindings for Google Play Services - Vision 71.1620.0-preview4
![Cap 2019-05-09 01-37-16-008](https://user-images.githubusercontent.com/42885949/57392378-93170480-71fb-11e9-92bd-0846d384f872.png)

**Comment by pulmuone** [comment]
> @pulmuone @61315
> Can you try preview4 please. And provide feedback here

Same Error.
Xamarin.Android Bindings for Google Play Services - Vision 71.1620.0-preview4

![Cap 2019-05-09 01-37-16-008](https://user-images.githubusercontent.com/42885949/57392415-a5913e00-71fb-11e9-9dd7-392b4245dee1.png)

**Comment by 61315** [comment]
All tests was done under 'Clean' environment. I cleaned the nuget cache, cleaned solution, manually removed the hidden bin & obj directory, deleted the app on the physical device and rebooted the IDE before and after each nuget packages install and application deployment.

- Visual Studio 2019 Preview 2
- Windows 10 1709 16299.1029
- Xamarin.Android 9.3.0.14
- Samsung SM-G900I (Android 6.0 - API 23)
- Target Android Version: Android 9.0 (API Level 28)

  - [x] Use Shared Runtime
  - [x] Use Fast Deployment
  - [x] Use aapt
  - [x] Use D8
  - [x] Use R8
  - [x] Use Concurrent GC
  - [x] Linking: None
  - [x] armeabi-v7a

### Xamarin.GooglePlayServices.Vision 71.1620.0-preview4

- What was expected?

  - User **can** create the Android.Gms.Vision.Faces.FaceDetector class and the Android.Gms.Vision.Faces.BarcodeDetector class by builder pattern, e.g., `var _detector = new FaceDetector.Builder(Application.Context).Build();`

- What was observed?

  - User **cannot** create the Android.Gms.Vision.Faces.FaceDetector class and the Android.Gms.Vision.Faces.BarcodeDetector class because the application has crashed with an unhandled exception.

> `var _detector = new FaceDetector.Builder(Application.Context).Build();`

> Unhandled Exception: Java.Lang.NoClassDefFoundError: com.google.android.gms.vision.face.internal.client.zza

> 05-08 22:33:15.909 D/Mono    (10418): Loading reference 1 of /storage/emulated/0/Android/data/com.frustrating.hello/files/.__override__/Xamarin.GooglePlayServices.Vision.dll asmctx DEFAULT, looking for Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
05-08 22:33:15.909 D/Mono    (10418): Assembly Ref addref Xamarin.GooglePlayServices.Vision[0xade0bc80] -> Mono.Android[0xade0bce0]: 14
05-08 22:33:15.909 D/Mono    (10418): Loading reference 2 of /storage/emulated/0/Android/data/com.frustrating.hello/files/.__override__/Xamarin.GooglePlayServices.Vision.dll asmctx DEFAULT, looking for Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
05-08 22:33:15.909 D/Mono    (10418): Assembly Ref addref Xamarin.GooglePlayServices.Vision[0xade0bc80] -> Java.Interop[0xade0bd40]: 5
05-08 22:33:15.909 D/Mono    (10418): Loading reference 0 of /storage/emulated/0/Android/data/com.frustrating.hello/files/.__override__/Xamarin.GooglePlayServices.Vision.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
05-08 22:33:15.909 D/Mono    (10418): Assembly Ref addref Xamarin.GooglePlayServices.Vision[0xade0bc80] -> mscorlib[0xa953ed60]: 18
05-08 22:33:15.919 D/Mono    (10418): DllImport searching in: '__Internal' ('(null)').
05-08 22:33:15.919 D/Mono    (10418): Searching for 'java_interop_jnienv_new_string'.
05-08 22:33:15.919 D/Mono    (10418): Probing 'java_interop_jnienv_new_string'.
05-08 22:33:15.919 D/Mono    (10418): Found as 'java_interop_jnienv_new_string'.
05-08 22:33:15.919 D/Mono    (10418): DllImport searching in: '__Internal' ('(null)').
05-08 22:33:15.919 D/Mono    (10418): Searching for 'java_interop_jnienv_get_static_object_field'.
05-08 22:33:15.919 D/Mono    (10418): Probing 'java_interop_jnienv_get_static_object_field'.
05-08 22:33:15.919 D/Mono    (10418): Found as 'java_interop_jnienv_get_static_object_field'.
05-08 22:33:15.929 I/art     (10418): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.vision.face.internal.client.zza>
05-08 22:33:15.929 I/art     (10418): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.vision.face.internal.client.zza>
05-08 22:33:15.929 I/art     (10418): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.vision.face.internal.client.zza>

> `var _detector = new BarcodeDetector.Builder(Application.Context).Build();`

> Unhandled Exception: Java.Lang.NoClassDefFoundError: com.google.android.gms.internal.vision.zzg

> 05-08 22:38:55.739 D/Mono    (11188): Loading reference 1 of /storage/emulated/0/Android/data/com.frustrating.hello/files/.__override__/Xamarin.GooglePlayServices.Vision.dll asmctx DEFAULT, looking for Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
05-08 22:38:55.739 D/Mono    (11188): Assembly Ref addref Xamarin.GooglePlayServices.Vision[0xade0be00] -> Mono.Android[0xade0be60]: 14
05-08 22:38:55.739 D/Mono    (11188): Loading reference 2 of /storage/emulated/0/Android/data/com.frustrating.hello/files/.__override__/Xamarin.GooglePlayServices.Vision.dll asmctx DEFAULT, looking for Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065
05-08 22:38:55.739 D/Mono    (11188): Assembly Ref addref Xamarin.GooglePlayServices.Vision[0xade0be00] -> Java.Interop[0xade0bec0]: 5
05-08 22:38:55.739 D/Mono    (11188): Loading reference 0 of /storage/emulated/0/Android/data/com.frustrating.hello/files/.__override__/Xamarin.GooglePlayServices.Vision.dll asmctx DEFAULT, looking for mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
05-08 22:38:55.739 D/Mono    (11188): Assembly Ref addref Xamarin.GooglePlayServices.Vision[0xade0be00] -> mscorlib[0xade0a1e0]: 18
05-08 22:38:55.749 D/Mono    (11188): DllImport searching in: '__Internal' ('(null)').
05-08 22:38:55.749 D/Mono    (11188): Searching for 'java_interop_jnienv_new_string'.
05-08 22:38:55.749 D/Mono    (11188): Probing 'java_interop_jnienv_new_string'.
05-08 22:38:55.749 D/Mono    (11188): Found as 'java_interop_jnienv_new_string'.
05-08 22:38:55.749 D/Mono    (11188): DllImport searching in: '__Internal' ('(null)').
05-08 22:38:55.749 D/Mono    (11188): Searching for 'java_interop_jnienv_get_static_object_field'.
05-08 22:38:55.749 D/Mono    (11188): Probing 'java_interop_jnienv_get_static_object_field'.
05-08 22:38:55.749 D/Mono    (11188): Found as 'java_interop_jnienv_get_static_object_field'.
05-08 22:38:55.759 I/art     (11188): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.vision.zzg>
05-08 22:38:55.759 I/art     (11188): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.vision.zzg>
05-08 22:38:55.769 I/art     (11188): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.internal.vision.zzg>

### Xamarin.Firebase.ML.Vision 71.1700.0-preview4

- What was expected?

  - User **can** create or reference the Firebase.ML.Vision.FirebaseVision class via FirebaseVision.GetInstance() method or FirebaseVision.Instance property.

  - User **can** instantiate the following classes from FirebaseVision class instance.
    - FirebaseVisionFaceDetector getVisionFaceDetector()
    - FirebaseVisionTextRecognizer getOnDeviceTextRecognizer()
    - FirebaseVisionTextRecognizer getCloudTextRecognizer()
    - FirebaseVisionBarcodeDetector getVisionBarcodeDetector()
    - FirebaseVisionLabelDetector getVisionLabelDetector()
    - FirebaseVisionCloudLabelDetector getVisionCloudLabelDetector()
    - FirebaseVisionDocumentTextRecognizer getCloudDocumentTextRecognizer()
    - FirebaseVisionCloudLandmarkDetector getVisionCloudLandmarkDetector()
    - FirebaseVisionFaceDetector getVisionFaceDetector()

- What was observed?

  - User **can** create or reference the FirebaseVision class via FirebaseVision.GetInstance() method or FirebaseVision.Instance property.
  - User **cannot** instantiate the following classes from FirebaseVision class instance because the expected classes were missing(double-checked with the Object Browser.)
    - FirebaseVisionFaceDetector getVisionFaceDetector()
    - ~FirebaseVisionTextRecognizer getOnDeviceTextRecognizer()~ Available as a property.
    - ~FirebaseVisionTextRecognizer getCloudTextRecognizer()~ Available as a method and a property.
    - FirebaseVisionBarcodeDetector getVisionBarcodeDetector()
    - FirebaseVisionLabelDetector getVisionLabelDetector()
    - FirebaseVisionCloudLabelDetector getVisionCloudLabelDetector()
    - FirebaseVisionDocumentTextRecognizer getCloudDocumentTextRecognizer()
    - FirebaseVisionCloudLandmarkDetector getVisionCloudLandmarkDetector()
    - FirebaseVisionFaceDetector getVisionFaceDetector()


I think the issue #200 and #206 should be reopened.

**Comment by KthProg** [comment]
I'm still getting these errors on `preview4`:

```Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'FirebaseVision' does not contain a definition for 'GetVisionBarcodeDetector' and no accessible extension method 'GetVisionBarcodeDetector' accepting a first argument of type 'FirebaseVision' could be found (are you missing a using directive or an assembly reference?)	OneControl.Android	C:\Users\khooks\Desktop\repos\onecontrol.mobile\OneControl\OneControl.Android\Services\LabelReader.cs	75	Active
Error	CS0246	The type or namespace name 'FirebaseVisionBarcodeDetector' could not be found (are you missing a using directive or an assembly reference?)	OneControl.Android	C:\Users\khooks\Desktop\repos\onecontrol.mobile\OneControl\OneControl.Android\Services\LabelReader.cs	75	Active
```
