### ISSUE TITLE
Xamarin.Firebase.Iid not compatible with netstandard2.0

### ISSUE THREAD

**Issue by jrahma** [xamarin/GooglePlayServicesComponents#245]
Hi,

I am getting this:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Xamarin.Firebase.Iid 71.1710.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Xamarin.Firebase.Iid 71.1710.0 supports: monoandroid90 (MonoAndroid,Version=v9.0)	Jafaria	C:\Users\jrahm\Source\Repos\Jafaria\Jafaria\Jafaria\Jafaria.csproj	1	

Kindly help...

Thanks,
[Jassim](https://www.softnames.com)

**Comment by Redth** [comment]
You are trying to install this package to a Netstandard 2.0 project which is not supported.  You can only install these packages to Xamarin.Android projects.

**Comment by iooovolts** [comment]
@Redth  but you can install 60.1142.1 on a .NET Standard project

**Comment by moljac** [comment]
@iooovolts I think you got it wrong. I'll make repro sample for this issue.

Android.Support and Google.Play.Services are platform specific (Android only) packages. How would one expect Android-only project to run on iOS or UWP if it would be added to `netstandard2.0` project?

You can add `netstandard2.0` project/library to `monodroidX.Y` because it is subset of it, but not other way around.

**Comment by steve-bpi** [comment]
@moljac no what you're saying makes complete sense. But I was able to install it, and these tutorials that show how to use Firebase analytics with Xamarin.Forms ask you to download Xamarin.Firebase.Core to your .NET Standard Project. Unless I read everything completley wrong.

**Comment by OliverONeillNG** [comment]
Make sure you are installing nuget packages into the android project in xamarin. For example, in a xamarin forms solution you will have 3 projects. I tried to install Xamarin.Google.Dagger into the main forms project instead of the android project and got a similar error.
