### ISSUE TITLE
Xamarin.Firebase.Messaging new release

### ISSUE THREAD

**Issue by cosminstirbu** [xamarin/GooglePlayServicesComponents#307]
Hello,

The latest Xamarin.Firebase.Messaging (71.1740.0) has a transitive dependency to Xamarin.Android.Support.v4 (via Xamarin.GooglePlayServices.Basement).

Is there a new release scheduled that would instead leverage AndroidX?

This is currently our only dependency that still forces us to use the migration package.

Thank you,
Cosmin

**Comment by rsgrey** [comment]
This is a very important dependency, without it the use of androidx is impossible!

**Comment by moljac** [comment]
See:

https://github.com/xamarin/GooglePlayServicesComponents/tree/master_based_androidx

and 

https://github.com/xamarin/GooglePlayServicesComponents/tree/master_based_androidx_based_updates_202002

Some users are building themselves, (https://github.com/xamarin/GooglePlayServicesComponents/issues/308), because CI builds (which are mandatory) have issues with building samples.

Bottom line -  NO release scheduled. It could be tomorrow, but I would not bet.

**Comment by rsgrey** [comment]
Hi! Are there any planned release dates?

**Comment by mattgraham1** [comment]
Any updates on this as the last update was from Native "Cloud Messaging version 17.4.0 - Update - February 26, 2019", but the most current one is "Cloud Messaging version 20.1.4 - Update - March 30, 2020"? That's over a year without any updates from the native libraries.

Please see the official Android release notes here: https://firebase.google.com/support/release-notes/android

**Comment by moljac** [comment]
@cosminstirbu @rsgrey @mattgraham1 

Fasten your seat belts:

https://github.com/xamarin/GooglePlayServicesComponents/tree/100.20200429-androidx-previews01

Tagged. Waiting for CI Azure DevOps builds.

There is another set/wave of updates already waiting and update cadence should be higher after everything builds.

**Comment by moljac** [comment]
Closing this one
