### ISSUE TITLE
Update to Google Mobile Ads SDK version 18.3.0 as required for mediation adapters

### ISSUE THREAD

**Issue by dtaylorus** [xamarin/GooglePlayServicesComponents#316]
The ad mediation adapters required for my application in turn require a minimum Google Mobile Ads SDK version of 18.3.0, while the latest Xamarin.GooglePlayServices.Ads Nuget package only supports version 17.1.2.

Please update Xamarin.GooglePlayServices.Ads to support Google Mobile Ads SDK version 18.3.0.

**Comment by dtaylorus** [comment]
Google Mobile Ads SDK version 17.1.2 was [released December 3, 2018](https://developers.google.com/android/guides/releases#december_3_2018), a year and a half ago (!) and has been updated dozens of times since then.

Why is this component so far out of date? Is this repo being maintained anymore? It's scary to have such a heavy dependency on a component that is more than a year out of date.

Given how time consuming it is to create a binding for a dependency this complex, I don't see another reasonable alternative than to depend on this outdated repo, which is really making me desperate to find an alternative to building with Xamarin.

**Comment by moljac** [comment]
Dear @dtaylorus 
Thank you for your feedback, but we are (I am) aware of the problem and we are working to resolve the issue.

There are 2 branches with updated bindings:

https://github.com/xamarin/GooglePlayServicesComponents/tree/master_based_androidx

and 

https://github.com/xamarin/GooglePlayServicesComponents/tree/master_based_androidx_based_updates_202002

Which build everything but samples and a lot of decent and nice users use those branches to build nugets and use them in their apps.

**Comment by moljac** [comment]
My strictly personal opinion

> Google Mobile Ads SDK version 17.1.2 was released December 3, 2018, a year and a half ago (!) and has been updated dozens of times since then.

Don't you think there might be a reason for that?

> Why is this component so far out of date? Is this repo being maintained anymore? 

Brief view in the activity in the repo would tell you that it is still maintained. 

> It's scary to have such a heavy dependency on a component that is more than a year out of date.

Again: don't you think there might be a reason for that? 

> Given how time consuming it is to create a binding for a dependency this complex, 

No way. How did you find this out? Where can I read about it? No. that is scary almost like seasonal flu.

> I don't see another reasonable alternative than to depend on this outdated repo, which is really making me desperate to find an alternative to building with Xamarin.

A lot of users simply act, because this is OSS. Some of them ask how they can help and then they help. Usually Fork + P, some sith samples and feedback. 

I guess people are different.

**Comment by dtaylorus** [comment]
@moljac Thank you for the information on the branch.

Would you consider publishing said branch as a nuget? As a pre-release if it's not stable yet?

This way nice users won't have to bother you to find out there's a working branch and then figure out how to build and use their own nugets.

Also, it's good to know this work is being handled by someone with your expertise in bindings. I've tried creating some myself and it's a lot of work for sure, so thank you!

**Comment by moljac** [comment]
@dtaylorus 

> Thank you for the information on the branch.

No problems.

> Would you consider publishing said branch as a nuget? As a pre-release if it's not stable yet?

I would, but process does not let me. Simple as that. I opened 2 ACW errors few days ago which pop up during samples build. Yes. Those are bugs from our tools and we work on the solutions. Now, in my (strictly mine) opinion - I would publish PREVIEW nugets now, w/o fixing those, but I cannot. Sorry.

> This way nice users won't have to bother you to find out there's a working branch and then figure out how to build and use their own nugets.

I'm aware of that and you are not the 1st person that came up with this suggestion. For now, clone branch and use nugets from local feed.

This should suffice:

```
git clone -b master_based_androidx \
      https://github.com/xamarin/GooglePlayServicesComponents.git
cd GooglePlayServicesComponents/
dotnet tool uninstall --global Cake.Tool
dotnet tool install --global Cake.Tool
dotnet cake -t=clean ; dotnet cake -t=ci
```

NOTE: this branch does not have Ads 18.3.0 and other branch needs updates.

NOTE: build will take some time and will most likey choke on samples. Nugets will be in `./output/` folder.

NOTE: you can shorten (but not by much) builds with `nuget` instead of `ci` taget in cake invocation.

> Also, it's good to know this work is being handled by someone with your expertise in bindings. 

We always have had good gals and guys working on bindings, but the number is growing and priorities shift (in this case QA).

> I've tried creating some myself and it's a lot of work for sure, so thank you!

You are welcome. I'm doing my best to catch up with google's release cycles and our tooling.

ping me here if you need more help

**Comment by dtaylorus** [comment]
Thanks! I need Ads 18.3.0 or later for AdMob mediation, but I found another solution using IronSource instead so I'll revisit this once the official Nuget is released.
