### ISSUE TITLE
GPS + FB Build All samples with Cake script - R8 ACW error (sample built with Cake script `ci` target or `samples` target)

### ISSUE THREAD

**Issue by moljac** [xamarin/GooglePlayServicesComponents#317]
### Operating System & Version (eg: Mac OSX 10.11):

MacOSX and Windows

### Google Play Services Version (eg: 8.4.0):

GPS-FB with AndroidX dependencies:

https://github.com/xamarin/GooglePlayServicesComponents/tree/master_based_androidx

### Describe your Issue:

Building samples that reference all nugets fails with R8 error (ACW generation):

```
"D:\X\GPS-FB-ax\samples\all\BuildAll.sln" (Build target) (1) ->
"D:\X\GPS-FB-ax\samples\all\FbAll\FbBuildAll.csproj" (default target) (3) ->
(_CompileToDalvikWithD8 target) ->
  R8 : error : Program type already present: com.google.common.util.concurrent.ListenableFuture [D:\X\GPS-FB-ax\samples\all\FbAll\FbBuildAll.csproj]
```

### Steps to Reproduce (with link to sample solution if possible):

```
git clone -b master_based_androidx \
      https://github.com/xamarin/GooglePlayServicesComponents.git
cd GooglePlayServicesComponents/
dotnet tool uninstall --global Cake.Tool
dotnet tool install --global Cake.Tool
dotnet cake -t=clean ; dotnet cake -t=ci
```

NOTE: long build time!

### Include any relevant Exception Stack traces, build logs, adb logs:

```
"D:\X\GPS-FB-ax\samples\all\BuildAll.sln" (Build target) (1) ->
"D:\X\GPS-FB-ax\samples\all\FbAll\FbBuildAll.csproj" (default target) (3) ->
(_CompileToDalvikWithD8 target) ->
  R8 : error : Program type already present: com.google.common.util.concurrent.ListenableFuture [D:\X\GPS-FB-ax\samples\all\FbAll\FbBuildAll.csproj]
```

**Comment by jonpryor** [comment]
```
  R8 : error : Program type already present: com.google.common.util.concurrent.ListenableFuture [D:\X\GPS-FB-ax\samples\all\FbAll\FbBuildAll.csproj]
```

I believe the problem is caused by an App project referencing *both* the [Xamarin.Google.Guava.ListenableFuture](https://www.nuget.org/packages/Xamarin.Google.Guava.ListenableFuture/) *and* [Xamarin.Google.Guava](https://www.nuget.org/packages/Xamarin.Google.Guava/) NuGet packages, which *each* provide the `com.google.common.util.concurrent.ListenableFuture` type.

*A* solution is a variation of Don't Do That™: if both packages are provided, only *one* of the `.jar` files should *actually* be referenced.

How do we do that?

A possible solution would be to update `Xamarin.Google.Guava.targets` within the Xamarin.Google.Guava NuGet so that it sets a `$(_HaveFullGuava)` property:

```xml
<PropertyGroup>
  <_HaveFullGuava>True</_HaveFullGuava>
</PropertyGroup>
```

We can then update `Xamarin.Googe.Guava.ListenableFuture.targets` to check for this property and only include its `.jar` file if `$(_HaveFullGuava)` *isn't* set:

```xml
<ItemGroup Condition=" '$(_HaveFullGuava)' != 'True' ">
  <AndroidJavaLibrary Include="$(MSBuildThisFileDirectory)*.jar" />
</ItemGroup>
```

In theory -- and entirely untested -- this *should* resolve the `r8` error, because with this setup we'll only include one `.jar` which defines `com.google.common.util.concurrent.ListenableFuture`.

However, there is an issue with this sketched out solution: ordering.  For it to work, the referencing App `.csproj` *must* `<Import/>` the `Xamarin.Google.Guava.targets` file *before* it imports the `Xamarin.Googe.Guava.ListenableFuture.targets` file.  This is Less Than Ideal™.

An alternative idea is for `Xamarin.Google.Guava.targets` to provide a `<Target/>` which *removes* the `.jar` files which `Xamarin.Googe.Guava.ListenableFuture.targets` adds.  However, I'm not sure where in the build target "chain" to insert such a target to do this removal.

**Comment by moljac** [comment]
XBD downgraded to 0.7.0

https://github.com/xamarin/GooglePlayServicesComponents/blob/master/source/GooglePlayServicesProject.cshtml#L204-L216

GooglePlayServicesProject.cshtml

```
@*
  <!--
  NOTE: 
  Xamarin.Build.Download version set in GooglePlaySericesProjects.cshtml template is 
  important for attributes in GooglePlaySericesTargets.cshtml template
  
  XamarinBuildDownloadAndroidAarLibrary   v >=  0.10.0
  XamarinBuildDownloadRestoreAssemblyAar  v <   0.10.0
  -->
  *@
  <ItemGroup>
    <PackageReference Include="Xamarin.Build.Download" Version="0.7.0" />
  </ItemGroup>
```

GooglePlayServicesTargets.cshtml

```
    <ItemGroup>
        @*
        <!--
        NOTE: 
        Xamarin.Build.Download version set in GooglePlaySericesProjects.cshtml template is 
        important for attributes in GooglePlaySericesTargets.cshtml template
        
        XamarinBuildDownloadAndroidAarLibrary   v >=  0.10.0
        XamarinBuildDownloadRestoreAssemblyAar  v <   0.10.0
        -->
        *@
      <XamarinBuildDownloadRestoreAssemblyAar Include="$(XamarinBuildDownloadDir)@(xbdAarPath)" />
    </ItemGroup>
```

https://github.com/xamarin/GooglePlayServicesComponents/blob/master/source/GooglePlayServicesTargets.cshtml#L59-L71

**Comment by moljac** [comment]
Not closing until Guava issue is solved!
