### ISSUE TITLE
NU1202: Package Xamarin.GooglePlayServices.Maps 71.1610.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0).

### ISSUE THREAD

**Issue by jphellemons** [xamarin/GooglePlayServicesComponents#318]
Start a new Xamarin Forms project and try to add the nuget for the `Xamarin.GooglePlayServices.Maps` will give this error because it's targetting monoandroid 9 instead of netstandard 2. Please rebuild the nuget so that it also supports netstandard 2.x

**Comment by leonluc-dev** [comment]
As far as I know, It's because the package `Xamarin.GooglePlayServices.Maps` is an Android-only library meant for platform specific Xamarin.Android projects. Hence why it's unable to be added to cross-platform Xamarin.Forms projects.

You might want to look in cross-platform Forms-based solutions for map functionality such as the [Xamarin.Forms map package](https://www.nuget.org/packages/Xamarin.Forms.Maps/) (which uses Apple Maps on iOS or Google Maps on Android). For which documentation can be found [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/)

If you need Google Maps on iOS as well (rather than Apple Maps) you can look into a third party package like [Xamarin.Forms.GoogleMaps](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/) ([Documentation](https://github.com/amay077/Xamarin.Forms.GoogleMaps))

**Comment by jphellemons** [comment]
Thanks. The kml I wanted to use had no lat lng. So I've read it with
sharpkml and geocoded each placemark

Op ma 6 apr. 2020 12:53 schreef leonluc-dev <notifications@github.com>:

**Comment by moljac** [comment]
@jphellemons 
@leonluc-dev is right. AndroidX, Android.Support, GooglePlayServices+Firebase are Android only packages, so no need to build them as netstandard20. GooglePlayServicesForIOS is completely other repo and targets iOS only (not netstandard20). This might have been source of confusion.

Closing this one.
