### ISSUE TITLE
Android.Gms.Auth.Api.SignIn.GoogleSignIn.GetSignedInAccountFromIntentAsync should be static

### ISSUE THREAD

**Issue by tomas-dainovec** [xamarin/GooglePlayServicesComponents#320]
All generated methods in `GoogleSignIn` class are static so addition method should be static too.

https://github.com/xamarin/GooglePlayServicesComponents/blob/af4d43bc6812315b2569d511da007cde0c2fb83c/source/com.google.android.gms/play-services-auth/Additions/TaskExtensions.cs#L10

**Comment by moljac** [comment]
In order to keep backward compatibility with non static API made by mistake following trick was implemented, but it was overkill

```
    public partial interface IAsyncGoogleSignIn
    {
        Task<GoogleSignInAccount> GetSignedInAccountFromIntentAsync(Intent intent);
    }


    public partial class GoogleSignIn : IAsyncGoogleSignIn
    {
        static Task<GoogleSignInAccount> GetSignedInAccountFromIntentAsync (Intent intent)
        {
            return GetSignedInAccountFromIntent (intent).AsAsync<GoogleSignInAccount>();
        }

        Task<GoogleSignInAccount> IAsyncGoogleSignIn.GetSignedInAccountFromIntentAsync(Intent intent)
        {
            return GetSignedInAccountFromIntent (intent).AsAsync<GoogleSignInAccount>();
        }
    }
```

Overkill because non-static method would have to be cast to interface to be used:

```
(IAsyncGoogleSignIn) ( new GoogleSignIn().GetSignedInAccountFromIntentAsync(i) );
```

So, the non-static code must be rewritten anyway.

Removing non-static member method though it is breaking change.

**Comment by moljac** [comment]
Fixed. Closing.
