### ISSUE TITLE
Difference between Xamarin.Firebase.Analytics and .Impl?

### ISSUE THREAD

**Issue by MihaMarkic** [xamarin/GooglePlayServicesComponents#367]
I can't find any relevant info what's the difference between Xamarin.Firebase.Analytics and Xamarin.Firebase.Analytics.Impl packages?
I'm looking into Xamarin Android usage, not Forms.

**Comment by moljac** [comment]
@MihaMarkic Not sure either. I have no time do dig deeper into those.

[Grabbing info from mvnrepository]

Seems like `Impl` might be old one. It was not updated since 2019-02. And seems like it was used by several other packages...  (FB.Analytics, FB.Messaging, FB.Config and FB.Crash and some GPS packages)

https://mvnrepository.com/artifact/com.google.firebase/firebase-analytics-impl/usages

if this helps. please close the issue.

**Comment by MihaMarkic** [comment]
Hi @moljac 

Ah, I initially thought it was something Xamarin specific, but it is merely a binding to two different Android libraries. The odd thing is that most samples use both. I'll check on Android side then, thanks.
