### ISSUE TITLE
Xamarin Forms: Firebase Messages are only randomly received

### ISSUE THREAD

**Issue by escamoteur** [xamarin/GooglePlayServicesComponents#43]
### Xamarin.Android Version (eg: 6.0):
6

Firebase.Messaging 32.940-beta3 (last one that can be installed together with Forms)

### Describe your Issue:

I have the problem that after some deploys my App does receive Notifications without problems, other completely don't.

I have no clue where to start searching. It seems to be working only when the last version of the App is uninstalled and the App is in release mode, But even that is not for certain.

Any help where to start searching would be great.

I'm really frustrated.

Thomas

**Comment by Redth** [comment]
First let's identify what IDE you're using.  Visual Studio (if so, which version) or Xamarin Studio?

Then we need to be able to reliably reproduce this issue in order to have a hope in tracking down a bug.  I would try something like this:

1. Install a debug build, send a notification, see if it arrives.
2. Clean and rebuild, and install a newly built version of the debug build (with the same actual app version in the  apk), see if the notification arrives or not.

Once we can establish a known way to cause notifications to not be sent, we can investigate _why_.

**Comment by Redth** [comment]
A little bit more on this.

We've had other users hint at what might be related problems with Firebase Messaging (not specific to Xamarin.Forms).  After some testing it looks like Visual Studio 2017 mostly works correctly, the only issue I've been able to reproduce is that when the app is in the background, and a notification arrives, breakpoints don't seem to hit while debugging.  The code still executes correctly, just breakpoints are not hit.

I can't reproduce any issues on Mac, in Xamarin Studio or Visual Studio for Mac.

**Comment by Redth** [comment]
Tracking this in #57
