### ISSUE TITLE
Glide.DiskLruCache cannot find annotations.jar

### ISSUE THREAD

**Issue by elomonaco** [xamarin/GooglePlayServicesComponents#545]
### Xamarin.Android Version (eg: 6.0):
12.0.0.3

### Operating System & Version (eg: Mac OSX 10.11):
Windows 10

### Describe your Issue
Whenever I try to build my Xamarin.Android app I get an error stating that it can't find a file named annotations.jar, if I go looking for it it is indeed not where it's expecting to be so my app is currently bricked (not building).

I have deleted the bin and obj folder and deleted the nuget folder and restored and clean solution but still it's not building successfully.

If I downgrade to 4.12.0.2 it builds just fine.

### Relevant information
this is the full error from msbuild

```
Xamarin.Android.Common.targets(771, 3): [XACDJ7028] System.IO.FileNotFoundException: Could not find file 'C:\Users\XamUser\.nuget\packages\xamarin.android.glide.disklrucache\4.12.0.4\buildTransitive\monoandroid10.0\..\..\jar\annotations.jar'.
File name: 'C:\Users\elomonaco\.nuget\packages\xamarin.android.glide.disklrucache\4.12.0.4\buildTransitive\monoandroid10.0\..\..\jar\annotations.jar'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at Xamarin.Android.Tasks.MonoAndroidHelper.SizeAndContentFileComparer.GetHashCode(FileInfo obj)
   at System.Linq.Set`1.InternalGetHashCode(TElement value)
   at System.Linq.Set`1.Find(TElement value, Boolean add)
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xamarin.Android.Tasks.MonoAndroidHelper.DistinctFilesByContent(IEnumerable`1 filePaths)
   at Xamarin.Android.Tasks.CheckDuplicateJavaLibraries.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17
```

Packages used:

```
<PackageReference Include="Xamarin.Android.Glide" Version="4.12.0.4" />
<PackageReference Include="Xamarin.Android.Glide.Annotations" Version="4.12.0.4" />
<PackageReference Include="Xamarin.Android.Glide.DiskLruCache" Version="4.12.0.4" />
<PackageReference Include="Xamarin.Android.Glide.GifDecoder" Version="4.12.0.4" />
```

Build settings (tools)

```
    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidEnableDesugar>true</AndroidEnableDesugar>
```

**Comment by bpater-tp** [comment]
same here

**Comment by Macjon** [comment]
Same here

**Comment by justintoth** [comment]
+1

**Comment by FANMixco** [comment]
This bug still persists.

**Comment by FANMixco** [comment]
I'm wondering if this will ever be fixed.

**Comment by elomonaco** [comment]
beats me, I'm migrating away from Xamarin, Microsoft doesn't seem to be putting enough attention into this part of their framework so I'm going native.

**Comment by petro2050** [comment]
Microsoft, please fix this. We're all blocked here.

**Comment by FANMixco** [comment]
@jpobst, do you know if this serious bug can be fixed? It seems a library was not added to the package. Thanks.

**Comment by jpobst** [comment]
@moljac It looks like the `.targets` were changed to look for `annotations.jar` instead of `disklrucache.jar` in this commit:
https://github.com/xamarin/GooglePlayServicesComponents/commit/4d15808905bbe77d493c9340279a06a03f94ac09#diff-a4978d07bcca3f8d657cf7b0d992192af4236b2afead0001e913aa9c95581701

However, the `.jar` in the NuGet is still called `disklrucache.jar`.  These need to match.

![image](https://user-images.githubusercontent.com/179295/160848426-f23f4a8a-e228-4783-b4c0-865850e8c60a.png)

**Comment by FANMixco** [comment]
And most likely, this is why people avoid certain versions in NuGet:

![image](https://user-images.githubusercontent.com/1666156/160986178-715da346-f520-42eb-8cc8-8adddd0222f4.png)

![image](https://user-images.githubusercontent.com/1666156/160986210-b1735ebc-631d-464b-8b9c-281d284b25d5.png)

**Comment by moljac** [comment]
> I don't think Glide is in this repo, maybe that is how we missed this issue? 

Gilde is in this repo since migrating to template sets.

https://github.com/xamarin/GooglePlayServicesComponents/tree/main/templates/glide

it was moved from XamarinComponents to this repo. Original location:

https://github.com/xamarin/XamarinComponents/tree/main/Android/Glide

> .NET MAUI is using Glide by default now, so I'm not sure how it's working there and not here.

IIRC, until recently MAUI was using older versions of AX and GPS-FB-MLKit packages. I must check `glide` template set and see if there was some mistake during migration.

**Comment by moljac** [comment]
BTW

Glide is the one using file lock issues during multitargeted builds on Mac (surprise). Not tested on windows.

https://github.com/xamarin/GooglePlayServicesComponents/blob/main/templates/glide/Project.cshtml#L3

reducing to 2 TFMs the problems are gone.

**Comment by FANMixco** [comment]
Hi @moljac, if this is not the correct place to report it the bug, can you guide us where to raise the issue? As you can see it's not a small bug and it's being forgotten for a while.

**Comment by moljac** [comment]
> Hi @moljac, if this is not the correct place to report it the bug, can you guide us where to raise the issue? 

This is the correct, the best and only one (kidding) place to report bugs. You did everything right.

Reporting on other sites/portals is making things a lot more difficult. Repo is maintained here and we have everything to do it here, so that is the reason it is preferred way.

> As you can see it's not a small bug and it's being forgotten for a while.

It was not forgotten, but I did not have time to dive in deeper.

I dove in and will report what was found.

**Comment by moljac** [comment]
fixed in

https://github.com/xamarin/GooglePlayServicesComponents/pull/593

**Comment by moljac** [comment]
> @moljac It looks like the `.targets` were changed to look for `annotations.jar` instead of `disklrucache.jar` in this commit: 

`*.targets` files were switched during template set migration. 

> However, the `.jar` in the NuGet is still called `disklrucache.jar`. These need to match.

`*.jar`s are OK. The content of the `*.targets` was wrong (looking for "other" jar)
