### ISSUE TITLE
Xamarin.Build.Download has been propagated into the nugets

### ISSUE THREAD

**Issue by vpenades** [xamarin/GooglePlayServicesComponents#647]
I've noticed Xamarin.Build.Download is a dependency in some nuget packages. I think this is a build only dependency and it should not appear in nuget packages; I guess it needs privateassets="all"

**Comment by moljac** [comment]
@vpenades 

Thanks for the feedback.

> ... Xamarin.Build.Download is a dependency in some nuget packages.

True. Based on license.

>  I think this is a build only dependency and it should not appear in nuget packages; I guess it needs privateassets="all".

It is build dependency and for the finall product - apps. It downloads maven binaries which must be packaged in your app in order to function properly.

Yes, managed code is in dll in the nuget, but you will need maven package too... And this is where XBD kicks in.
