### ISSUE TITLE
Is it support RewardedAds?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/GooglePlayServicesComponents#72]
Is it support RewardedAds?
If yes, please give me link docs and sample
Thank you!

**Comment by Redth** [comment]
It should be if it's a part of the Google Play Services / Firebase libraries for Android since we simply bind them.

Google has some documentation on getting this setup which will be very similar to how you would set it up in Xamarin. https://developers.google.com/admob/android/rewarded-video

Please open a new issue if you find there are specific API's missing from the [Nuget package](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Ads/)
