### ISSUE TITLE
MlKitAnalyzer missing

### ISSUE THREAD

**Issue by haavamoa** [xamarin/GooglePlayServicesComponents#839]
### Xamarin.Android Version (eg: 6.0):
net8.0-android

### Operating System & Version (eg: Mac OSX 10.11):
macOS Sonoma 14.2.1

### Google Play Services Version

`Xamarin.Google.MlKit.BarcodeScanning" Version="117.2.0"`

### Describe your Issue
I am trying to build a barcode scanning app using CameraX and MLKit barcode scanning. Following this guide,[ I am unable to proceed from here](https://developer.android.com/media/camera/camerax/mlkitanalyzer#implement-mlkitanalyzer). 

I am faced with an issue where I am unable to find `MlKitAnalyzer`.
![image](https://github.com/xamarin/GooglePlayServicesComponents/assets/2527084/4ade9b2b-d7ab-419c-969e-0c02b35c0e62)

### Relevant information

Add relevant project settings from `*.csproj` file:

Packages used:

```
  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.Camera.Camera2" Version="1.3.1" />
    <PackageReference Include="Xamarin.AndroidX.Camera.View" Version="1.3.1" />
    <PackageReference Include="Xamarin.Google.Android.Material" Version="1.10.0.2" />
    <PackageReference Include="Xamarin.Google.MlKit.BarcodeScanning" Version="117.2.0" />
  </ItemGroup>
```

### Minimal Repro Code Sample

https://github.com/haavamoa/CameraXSamples/tree/master/CameraXMlKit

### Steps to Reproduce (with link to sample solution if possible):

1. Fork repository 
2. Try to build CameraXMlKit

### Include any relevant Exception Stack traces, build logs, adb logs:

`MainActivity.cs(46,31): Error CS0246 : The type or namespace name 'MlKitAnalyzer' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by moljac** [comment]
@haavamoa 

Thanks for the feedback and sorry for late reply.

According to

https://developer.android.com/reference/androidx/camera/mlkit/vision/MlKitAnalyzer.Result

`MlKitAnalyzer` is in `androidx.camera:camera-mlkit-vision` artifact which is not bound yet:

https://www.nuget.org/packages?q=androidx.camera

https://maven.google.com/web/index.html?q=androidx.camera#androidx.camera:camera-mlkit-vision

It is not bound, because it is in preview.

Closing this issue. Please open issue when package is released as stable version.

Thanks
